Change generic yaml.load() references to use safe_load()
CentOS-PaaS-SIG/linchpin pull request #1769
Opened 2021-10-21 08:50 UTC by jordigilh

This PR aims to update a few references in the code that used the `yaml.load()` function and didn't specify the `Loader` argument to use. Instead, the code has been changed to use the `yaml.safe_load()` function. The change is required because starting from PyYAML 6.0, the `Loader` argument is now mandatory for the `load()` call.

Here is an example of the output of running linchpin with PyYAML 6.0:

```
Error executing hook: 'load() missing 1 required positional argument: 'Loader''
```

The `safe_load()` function uses the `SafeLoader` loader, which is [considered to be safe](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning) for loading untrusted input. 

The PyYAML library has deprecated the `yaml.load()` without the `Loader` argument as it considers it insecure when [not specifying the loader argument](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation).

Note: there are references in the code that uses the `FullLoader` as the argument to the `yaml.load()` call. This loader is [not safe to use](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation#how-to-disable-the-warning). Let me know if the references should be changed to use the `SafeLoader` instead, so I can add them to this PR. For the time being, I will only change those that are not compatible with PyYAML 6.0 because of the deprecation.

Signed-off-by: Jordi Gil <jgil@redhat.com>

2021-10-21 08:53 UTC, jordigilh commented
@samvarankashyap can you help review this PR, or suggest someone else instead?  Much appreciated! :smile:

2021-10-25 15:12 UTC, jordigilh commented
Hi @junqizhang, can you take a look at this PR? 
/assign @junqizhang

2021-10-27 16:12 UTC, JunqiZhang0 requested changes
The tests are failing

2021-10-27 20:22 UTC, jordigilh commented
/retest

2021-10-27 20:24 UTC, jordigilh commented
> The tests are failing

They are failing in setting up the environment (downloading dependencies). I don't think my changes are the culprit for this error. Is there any way I can retest?
```
/90b8d4cd611ac2aa526290ae4b4285aa5ea57ee191c63c2f3d04170d7683/cryptography-35.0.0.tar.gz (559kB)
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7466vl0k/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

2021-11-09 17:17 UTC, JunqiZhang0 commented
[test]

2021-11-09 17:18 UTC, JunqiZhang0 commented
/retest

2021-11-09 23:06 UTC, jordigilh commented
@JunqiZhang0 can you trigger the tests? I think I've fixed the environment issue. Thanks :smile:

2023-06-21 19:26 UTC, closed without merging